"""empty message

Revision ID: 0ffac9748094
Revises: dc9702f2b1c9
Create Date: 2022-07-03 15:49:31.420175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ffac9748094'
down_revision = 'dc9702f2b1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biggest_buy_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('biggest_buy_campaign_id', sa.Integer(), nullable=True),
    sa.Column('buyer_address', sa.String(length=100), nullable=True),
    sa.Column('buyer_amount', sa.Integer(), nullable=True),
    sa.Column('transaction_link', sa.String(length=100), nullable=True),
    sa.Column('transaction_chain', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['biggest_buy_campaign_id'], ['biggest_buy_campaign.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raffle_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raffle_campaign_id', sa.Integer(), nullable=True),
    sa.Column('buyer_address', sa.String(length=100), nullable=True),
    sa.Column('buyer_amount', sa.Integer(), nullable=True),
    sa.Column('transaction_link', sa.String(length=100), nullable=True),
    sa.Column('transaction_chain', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.ForeignKeyConstraint(['raffle_campaign_id'], ['raffle_campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('transaction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('buyer_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('buyer_amount', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transaction_pkey')
    )
    op.drop_table('raffle_transaction')
    op.drop_table('biggest_buy_transaction')
    # ### end Alembic commands ###
