"""empty message

Revision ID: 8e1bf8aa526d
Revises: 0ffac9748094
Create Date: 2022-07-03 18:12:28.517291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1bf8aa526d'
down_revision = '0ffac9748094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biggest_buy_campaign', sa.Column('campaign_winner', sa.String(length=100), nullable=True))
    op.drop_column('biggest_buy_campaign', 'campaing_winner')
    op.add_column('raffle_campaign', sa.Column('campaign_winner', sa.String(length=100), nullable=True))
    op.drop_column('raffle_campaign', 'campaing_winner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raffle_campaign', sa.Column('campaing_winner', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('raffle_campaign', 'campaign_winner')
    op.add_column('biggest_buy_campaign', sa.Column('campaing_winner', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('biggest_buy_campaign', 'campaign_winner')
    # ### end Alembic commands ###
