"""empty message

Revision ID: 0ed0ee5e960f
Revises: 466b5877ffce
Create Date: 2022-08-22 14:15:45.286642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed0ee5e960f'
down_revision = '466b5877ffce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('min_amount', sa.Float(), nullable=True))
    op.drop_column('campaigns', 'minimum_buy_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('minimum_buy_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'min_amount')
    # ### end Alembic commands ###
