"""empty message

Revision ID: 12751cb43e86
Revises: ac9bbac81f2f
Create Date: 2022-08-04 10:57:41.419832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12751cb43e86'
down_revision = 'ac9bbac81f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('status', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'status')
    # ### end Alembic commands ###
