"""empty message

Revision ID: 2045d2802dd3
Revises: 826aabb421b9
Create Date: 2022-07-23 16:55:12.932715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2045d2802dd3'
down_revision = '826aabb421b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_subscription')
    op.drop_table('one_time_subscription')
    op.add_column('subscription', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.add_column('subscription', sa.Column('number_of_countable_subscriptions', sa.Integer(), nullable=True))
    op.add_column('subscription', sa.Column('is_life_time_subscription', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'is_life_time_subscription')
    op.drop_column('subscription', 'number_of_countable_subscriptions')
    op.drop_column('subscription', 'end_date')
    op.drop_column('subscription', 'start_date')
    op.create_table('one_time_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=4), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name='one_time_subscription_subscription_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_type.id'], name='one_time_subscription_subscription_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='one_time_subscription_pkey')
    )
    op.create_table('weekly_subscription',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subscription_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('number_of_weeks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], name='weekly_subscription_subscription_id_fkey'),
    sa.ForeignKeyConstraint(['subscription_type_id'], ['subscription_type.id'], name='weekly_subscription_subscription_type_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='weekly_subscription_pkey')
    )
    # ### end Alembic commands ###
