"""empty message

Revision ID: 26577fc68c31
Revises: 5a2a17b3b748
Create Date: 2022-10-14 10:13:36.173987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26577fc68c31'
down_revision = '5a2a17b3b748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('group', sa.Column('group_link', sa.Text(), nullable=True))
    op.add_column('tracked_token', sa.Column('min_usd_amount', sa.Float(), nullable=True))
    op.drop_index('fki_wallet_group_id_fkey', table_name='wallet')
    op.drop_constraint('wallet_group_id_fkey', 'wallet', type_='foreignkey')
    op.create_foreign_key(None, 'wallet', 'group', ['group_id'], ['group_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='foreignkey')
    op.create_foreign_key('wallet_group_id_fkey', 'wallet', 'group', ['group_id'], ['group_id'], ondelete='SET NULL')
    op.create_index('fki_wallet_group_id_fkey', 'wallet', ['group_id'], unique=False)
    op.drop_column('tracked_token', 'min_usd_amount')
    op.drop_column('group', 'group_link')
    op.drop_table('blacklist')
    # ### end Alembic commands ###
