"""empty message

Revision ID: 352a8e70a690
Revises: 78788ed93aa1
Create Date: 2023-02-23 14:38:04.978157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '352a8e70a690'
down_revision = '78788ed93aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_transactions', sa.Column('at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_transactions', 'at')
    # ### end Alembic commands ###
