"""empty message

Revision ID: 3aac81422305
Revises: 095af1e9230d
Create Date: 2022-07-12 17:34:31.711181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aac81422305'
down_revision = '095af1e9230d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('supported_exchange_chain_id_fkey', 'supported_exchange', type_='foreignkey')
    op.create_foreign_key(None, 'supported_exchange', 'supported_chain', ['chain_id'], ['id'])
    op.drop_constraint('supported_pairs_chain_id_fkey', 'supported_pairs', type_='foreignkey')
    op.create_foreign_key(None, 'supported_pairs', 'supported_chain', ['chain_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supported_pairs', type_='foreignkey')
    op.create_foreign_key('supported_pairs_chain_id_fkey', 'supported_pairs', 'supported_chain', ['chain_id'], ['id'])
    op.drop_constraint(None, 'supported_exchange', type_='foreignkey')
    op.create_foreign_key('supported_exchange_chain_id_fkey', 'supported_exchange', 'supported_chain', ['chain_id'], ['id'])
    # ### end Alembic commands ###
