"""empty message

Revision ID: 466b5877ffce
Revises: fa9d421b2857
Create Date: 2022-08-16 15:36:21.890500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466b5877ffce'
down_revision = 'fa9d421b2857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'campaign_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('campaign_status', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
