"""empty message

Revision ID: 4ed71f6c9e0b
Revises: 12751cb43e86
Create Date: 2022-08-04 13:09:07.289227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed71f6c9e0b'
down_revision = '12751cb43e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('active_tracking', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_token', 'active_tracking')
    # ### end Alembic commands ###
