"""empty message

Revision ID: 4f58b4fb9f19
Revises: f9e6940e08ae
Create Date: 2023-02-23 16:04:08.960658

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f58b4fb9f19'
down_revision = 'f9e6940e08ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_transactions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_transactions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('buyer_address', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('buyer_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transaction_link', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('transaction_chain', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('group_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('token_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], name='all_transactions_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='all_transactions_pkey')
    )
    # ### end Alembic commands ###
