"""empty message

Revision ID: 5d7c9ae9e865
Revises: c953369ac53a
Create Date: 2022-08-15 06:49:45.157508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d7c9ae9e865'
down_revision = 'c953369ac53a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('advert', sa.Text(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('advertisement')
    # ### end Alembic commands ###
