"""empty message

Revision ID: 608ccba7314f
Revises: 0ed0ee5e960f
Create Date: 2022-08-22 14:19:45.500583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '608ccba7314f'
down_revision = '0ed0ee5e960f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('buyer_entry_amount', sa.Float(), nullable=True))
    op.drop_column('transactions', 'buyer_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('buyer_amount', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'buyer_entry_amount')
    # ### end Alembic commands ###
