"""empty message

Revision ID: 78788ed93aa1
Revises: 26577fc68c31
Create Date: 2023-02-23 14:26:49.264163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78788ed93aa1'
down_revision = '26577fc68c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_address', sa.String(length=100), nullable=True),
    sa.Column('buyer_amount', sa.Float(), nullable=True),
    sa.Column('transaction_link', sa.String(length=100), nullable=True),
    sa.Column('transaction_chain', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_transactions')
    # ### end Alembic commands ###
