"""empty message

Revision ID: 83849e5f1054
Revises: b6e1d3e1c987
Create Date: 2022-08-28 12:26:02.900692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83849e5f1054'
down_revision = 'b6e1d3e1c987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('active_tracking', sa.Boolean(), nullable=True))
    op.drop_column('tracked_token', 'active_trackingg')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('active_trackingg', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tracked_token', 'active_tracking')
    # ### end Alembic commands ###
