"""empty message

Revision ID: 8a0ff1e4ded5
Revises: 3aac81422305
Create Date: 2022-07-13 18:49:12.318019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0ff1e4ded5'
down_revision = '3aac81422305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supported_exchange', sa.Column('factory_address', sa.String(length=100)))
    op.create_unique_constraint(None, 'supported_exchange', ['factory_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supported_exchange', type_='unique')
    op.drop_column('supported_exchange', 'factory_address')
    # ### end Alembic commands ###
