"""empty message

Revision ID: a1cce20d6d6f
Revises: f24a35ebaf34
Create Date: 2022-07-12 14:57:00.441133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cce20d6d6f'
down_revision = 'f24a35ebaf34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'supported_chain', ['chain_id'])
    op.create_unique_constraint(None, 'supported_exchange', ['router_address'])
    op.create_unique_constraint(None, 'supported_pairs', ['pair_address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supported_pairs', type_='unique')
    op.drop_constraint(None, 'supported_exchange', type_='unique')
    op.drop_constraint(None, 'supported_chain', type_='unique')
    # ### end Alembic commands ###
