"""empty message

Revision ID: ac9bbac81f2f
Revises: ded3fe307400
Create Date: 2022-07-24 02:25:07.905930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac9bbac81f2f'
down_revision = 'ded3fe307400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('supported_chain', sa.Column('native_symbol', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supported_chain', 'native_symbol')
    # ### end Alembic commands ###
