"""empty message

Revision ID: b6e1d3e1c987
Revises: d2fa98912d58
Create Date: 2022-08-28 12:23:07.529123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e1d3e1c987'
down_revision = 'd2fa98912d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('active_trackingg', sa.Boolean(), nullable=True))
    op.drop_column('tracked_token', 'active_tracking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('active_tracking', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tracked_token', 'active_trackingg')
    # ### end Alembic commands ###
