"""empty message

Revision ID: ce56b612dad5
Revises: b92c868fc67b
Create Date: 2022-07-17 19:59:12.120341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce56b612dad5'
down_revision = 'b92c868fc67b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_dexs',
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['supported_exchange.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tracked_token.id'], )
    )
    op.create_table('token_pairs',
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('pair_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pair_id'], ['supported_pairs.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['tracked_token.id'], )
    )
    op.drop_constraint('token_chains_pair_id_fkey', 'token_chains', type_='foreignkey')
    op.drop_constraint('token_chains_exchange_id_fkey', 'token_chains', type_='foreignkey')
    op.drop_column('token_chains', 'pair_id')
    op.drop_column('token_chains', 'exchange_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token_chains', sa.Column('exchange_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('token_chains', sa.Column('pair_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('token_chains_exchange_id_fkey', 'token_chains', 'supported_exchange', ['exchange_id'], ['id'])
    op.create_foreign_key('token_chains_pair_id_fkey', 'token_chains', 'supported_pairs', ['pair_id'], ['id'])
    op.drop_table('token_pairs')
    op.drop_table('token_dexs')
    # ### end Alembic commands ###
