"""empty message

Revision ID: d2fa98912d58
Revises: f25d626db893
Create Date: 2022-08-24 19:19:23.306581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2fa98912d58'
down_revision = 'f25d626db893'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('prize', sa.Text(), nullable=True))
    op.drop_column('campaigns', 'award')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('award', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'prize')
    # ### end Alembic commands ###
