"""empty message

Revision ID: ded3fe307400
Revises: 2045d2802dd3
Create Date: 2022-07-24 02:05:17.744644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ded3fe307400'
down_revision = '2045d2802dd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('expected_amount_in_native_wei', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'expected_amount_in_native_wei')
    # ### end Alembic commands ###
