"""empty message

Revision ID: e7c80894d979
Revises: 4f58b4fb9f19
Create Date: 2023-02-24 16:49:24.627589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7c80894d979'
down_revision = '4f58b4fb9f19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_address', sa.String(length=100), nullable=True),
    sa.Column('buy_date', sa.DateTime(), nullable=True),
    sa.Column('buyer_amount', sa.Float(), nullable=True),
    sa.Column('token_name', sa.String(length=100), nullable=True),
    sa.Column('transaction_link', sa.String(length=100), nullable=True),
    sa.Column('transaction_chain', sa.String(length=20), nullable=True),
    sa.Column('group_id', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('all_transactions')
    # ### end Alembic commands ###
