"""empty message

Revision ID: efe976907dbb
Revises: a278d82be7cb
Create Date: 2022-09-01 17:02:39.904516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe976907dbb'
down_revision = 'a278d82be7cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracked_token', sa.Column('circulating_supply', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracked_token', 'circulating_supply')
    # ### end Alembic commands ###
