"""empty message

Revision ID: f25d626db893
Revises: f54f68cb9500
Create Date: 2022-08-24 19:17:31.722354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f25d626db893'
down_revision = 'f54f68cb9500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('award', sa.Text(), nullable=True))
    op.drop_column('campaigns', 'prize')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('prize', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.drop_column('campaigns', 'award')
    # ### end Alembic commands ###
