"""empty message

Revision ID: f54f68cb9500
Revises: 608ccba7314f
Create Date: 2022-08-22 14:22:36.989654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f54f68cb9500'
down_revision = '608ccba7314f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('buyer_amount', sa.Float(), nullable=True))
    op.drop_column('transactions', 'buyer_entry_amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('buyer_entry_amount', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'buyer_amount')
    # ### end Alembic commands ###
