"""empty message

Revision ID: f9e6940e08ae
Revises: 352a8e70a690
Create Date: 2023-02-23 15:06:15.963474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e6940e08ae'
down_revision = '352a8e70a690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_transactions', sa.Column('token_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_transactions', 'token_name')
    # ### end Alembic commands ###
