"""empty message

Revision ID: fa9d421b2857
Revises: 5d7c9ae9e865
Create Date: 2022-08-15 06:52:53.630188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa9d421b2857'
down_revision = '5d7c9ae9e865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_competition')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_competition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('competition_type', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('competition_id', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.group_id'], name='active_competition_group_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='active_competition_pkey')
    )
    # ### end Alembic commands ###
